### ISSUE TITLE
Unable to read Realm: No such object while initializing kadmin.local interface

### ISSUE THREAD

**Issue by petermasica** [nugaon/docker-kerberos-with-ldap#1]
Hi,
I had a look at a few of your repos and tried setting up ldap & kerberos dev env, but I didn't succeed. I'm all new to this, so my understanding of all of this is very limited and I'd be very grateful if you could elaborate on I what did wrong. 

docker-compose.yml
```
version: '3'
services:
  ldap:
    image: osixia/openldap:1.4.0
    container_name: ldap
    volumes:
      - ./ldap/database:/var/lib/ldap
      - ./ldap/config:/etc/ldap/slapd.d
    ports:
      # LDAP
      - 389:10389
      # LDAPS
      # - 636:10636

  kerberos:
    image: nugaon/kerberos-with-ldap
    container_name: kerberos
    volumes:
      - /dev/urandom:/dev/random
    environment:
      - REALM=EXAMPLE.ORG
      - DOMAIN_REALM=example.org
      - SEARCH_DOMAINS=example.org
      - LDAP_DC=dc=example,dc=org

  phpldapadmin:
    image: osixia/phpldapadmin:latest
    container_name: phpldapadmin
    environment:
      PHPLDAPADMIN_LDAP_HOSTS: 'ldap'
      PHPLDAPADMIN_HTTPS: 'false'
    ports:
      - '8080:80'
    depends_on:
      - ldap
```

After executing ` docker exec -ti kerberos kadmin.local -q 'addprinc -x dn=cn=Teszt" "Elek,cn=users,dc=ldap,dc=hiflylabs,dc=hu telek'` which you mentioned in your examples I get the following error:
```
Authenticating as principal root/admin@EXAMPLE.ORG with password.
kadmin.local: Unable to read Realm: No such object while initializing kadmin.local interface
```

Also, what would be the correct command to register `cn=admin,dc=example,dc=org` account with kerberos? Would this `docker exec -it kerberos kadmin.local -q 'addprinc -x cn=admin,dc=example,dc=org'` be correct?

Thanks in advance for your help.
